FROM kunstrasenspringer/test:latest

USER root
RUN apt-get update && apt install -y python

USER test
WORKDIR /home/test/travis_test
RUN chmod +x test.sh && ./test.sh
COPY test.py .
RUN python test.py
RUN echo "echo change" >> test.sh
