sudo: true
dist: trusty

jobs:
  include:
  - stage: build precice docker image
    script:
    - mkdir test1
  - stage: testing su2 and ccx
    script:
    - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    - docker build -f Dockerfile.su2_ccx -t su2_ccx .
  - script:
    - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    - docker build -f Dockerfile.openfoam -t openfoam .
