sudo: true
dist: trusty

jobs:
  include:
  - stage: build precice docker image
    script:
      - mkdir test
  - stage: testing
    - script:
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker build -f Dockerfile.su2_ccx -t su2_ccx .
    - script:
      - mkdir test1
      - cd test1
    - script:
      - mkdir test2
      - cd test2
