sudo: true
dist: trusty
jobs:
  include:
  - stage: first part
    script:
    - python push.py 1 of-ccx
env:
  global:
    secure: nW5kY8jg3nmGIu7fyVAMd4SX066/5ESFAKpDBTYjtkTSQ1t7+BScVarsS4esioAyQWAduCMC+BBG+F71R6NuohkpUxRx1b00f4CHHYz6RUdfHKeramhBoW8Mp9MWyFbXWNmv3JuVbXxlGORQp9s38YauwxBtHrzZiu6iajbYVBcgYV/niyBVJQtqrGBkiR9W5WAqkfaY7ls5hdrK7Ym6ltS2YoOAB9zllz4AZnSDc/3c3nIvLcCvsezlCtsgla1Ms2AVycxME3M/k1AEoEuuLMik2qRW5lAih0EQ1vpyVq41FJPYYEjM5D/sWPrP+JtjWgDn+n2tlbzfL8T7t+fImUjb9c1PwTY4abptwoyyNGtI/UVgtBCjkGvuNOJQsGSdMg1hEDBdv2scL3nvKqk8sJ9QPCPDu0QAmkUKyy9nyR/lW15ZI1V5gslbLV5KSk/0wM4QCYQ83K37g++qqE9LoemtfyW33gV5vKdHGQv6fp9GzGvAw+JJeojbR7NWPrM1UlOlBSEC7lbee3aUlpWEo/8VpnNZax8vZaSVSZcXrAGIfo+ACyN6MQlIefKzS2V6lne7wH48jQHegR7mQeihFR0Hp44LKJuZlkXKCwoE3iR00d50AvjgCz2VRGZNzTeWz2ReYgUVVker/h/rmOV2lJ0IU+DC7zoyI+CNhvxHxXc=
