sudo: true
dist: trusty
jobs:
  include:
  - stage: System Tests
    script:
    - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    - docker build -f Dockerfile.su2-ccx -t su2-ccx .
    - docker run -it -d --name su2-ccx_container su2-ccx
    - docker cp su2-ccx_container:/home/alice/Output_su2-ccx .
    - python compare_su2-ccx.py
    after_failure:
    - sh push.sh Output_su2-ccx
  - script:
    - docker build -f Dockerfile.of-of -t of-of .
    - docker run -it -d --name of-of_container of-of
    - docker cp of-of_container:/home/alice/Output_of-of .
    - python compare_of-of.py
    after_failure:
    - sh push.sh Output_of-of
  - script:
    - docker build -f Dockerfile.of-ccx -t of-ccx .
    - docker run -it -d --name of-ccx_container of-ccx
    - docker cp of-ccx_container:/home/alice/Output_of-ccx .
    - python compare_of-ccx.py
    after_failure:
    - sh push.sh Output_of-ccx
env:
  global:
    secure: lPoqC++lE1sZXX6PynOIgQDB9FFKOCQQQvE04UyDGceSp7mVXWrExksg6Z9xY3bhPUccxNGKrkeylXFkOok0Ad1OEiJ1p6K2eSTEhkHfUmOBAC68bpvpPkYYmdU4LrK53Zrk+W2nAlar5K8OMBjAwoU1+kR1bM1qju72m42+3K2U3dMYm4twee4wUdvL7RfdnAiUeQEcZX8pmoUUqF7jQIESk4NJ+92rKmbB7Qm7ntzp2weHv6cFo5RS/j6KqyUGBYnHVV/WReJqGUfDkPR20ONrfNwF5vuJ/xzuXlPwlFk0N3FEdDZYTKAj3EVGnhUBh9ndnraRV1k17vo+2LaTe5rqSKcJ6z3hOxQW3OfEgET8rZ5F5eM96/YPiq3WkclUH2jl9XRoGFhRtivAiyuwHuDBSZP4sIXtjLxykHFbioeS61yLchzaTbQbsqBlEiCfYsaI7Tk8BJlw+VPU+ZdfrZcxbLPwS5O6OB5KGWFdnpt4jJ3Fe/My5X3Ek+dB7baI5Tj9mNG7hMzaTHRPkm+cHVwnxzHkjtztxy2Pw1gvzbrbC51x9AedB1CT9B8pLtLFyZs/DrQhZbRgFw+Z0jWKUd47Exed/Bklg47c/qwQobKpsgd3OImDr9YtzpnifYi3MWg+2Dgr7D/RhQTKeMRB1i+tb4w1hE7aagEXHlrs28o=
